utilities:
  keywords:
    fizz:
    internet:
      - helix
    videotron-mobile:
      - mobile
    videotron:
    prime-video:
      - prime-video
      - primevideo
      - amazon.ca-prime
    apple-music:
      - music
    apple-icloud:
      - apple-icloud
      - icloud
    apple:
      - apple.com
      - apple-store
      - apple
    netflix:
    flexiti:
    richard-income:
      - keyword: interac-e-transfer
        amount: 40
hydro-electric:
  keywords:
    hydro-quebec:
transport:
  keywords:
    flo:
    stm-longueuil:
interest-earned:
  keywords:
    interest-earned:
medical:
  keywords:
    chiro:
      - chiro
      - chiropractor
    acupuncture:
    medavie-blue:
    transaction-withdrawal:
    clinique-dentaire:
tesla:
  keywords:
    car-payment:
      - rbc-loan-pymt
    car-insurance:
      - debit-to-promutuel36
mortgages:
  keywords:
    mortgage-payments:
      - debit-to-bnc
    mortgage-insurances:
      - pre-authorized-debit-to-beneva
    mortgage-taxes:
      - mortgages-taxes
groceries:
  keywords:
    super-c:
    wal-mart:
    provigo:
    couche-tard:
    iga:
    metro:
    maxi:
    ultramar:
    costco:
    fruiterie:
    jarochos:
    epicerie:
    boucherie-brunelle:
    filet-gourmet-vare:
    taiyo:
grocery_junk:
  keywords:
    saq:
    dollarama:
restaurants:
  keywords:
    tim-hortons:
    starbucks:
    mcdonald:
    harveys:
    dairy-queen:
      - dairy-queeen
      - dairy-queen
    uber-eats:
    arriba-burrito:
    sushi:
    gateau:
    subway:
    7853351-canada:
    arahova:
    thai-express:
    tikiming:
    montaza:
    benny:
    pizza:
    tit-reveil-varennes:
    poulet-rouge:
    alfa-hot-dog:
    restaurant:
pharmacy:
  keywords:
    jean-coutu:
    pharmaprix:
renovations:
  keywords:
    rona:
    cdn-tire:
    canac:
    facebk:
    tribunal:
    hydrosolution:
online-purchases:
  keywords:
    epic-games:
    jb-games:
    michaels:
    amazon:
      - amzn
      - amazon.
extra:
  keywords:
    winners:
    tabagie:
    bota-bota:
    agence-de-mobilite:
    lenca-canada:
    saaq:
banking_fee:
  keywords:
    programme-pratique:
    service-charge:
    fixed-monthly-fees:
    interac-e-transfer-service:
    monthly-transaction-fees:
andy_income:
  keywords:
    rental-income:
      - keyword: interac-e-transfer
        amount: 2100
    salary:
      - infoprimes
alex_income:
  keywords:
    rental-income:
      - keyword: interac-e-transfer
        amount: 2925
    salary:
      - alaya
scotia_credit_line:
  keywords:
    tf-0000000022182671725:
    scotialine:
unknown e-transfer in:
  keywords:
    transfer-in:
unknown e-transfer out:
  keywords:
    transfer-out:
