category:
  transport:
    - flo
    - stm-longueuil
  medical:
    - chiro
    - acupuncture
    - medavie-blue
    - transaction-withdrawal  # psychologue carole
  monthly_alex:
    - fizz
    - hydrosolution
  tesla:
    - rbc-loan-pymt  # tesla car payment
  mortgage:
    - banque-nationale  # mortgage condo and valois
  insurance:
    - preauthorized-debit-beneva  #mortgage insurance
    - a5100101283-001-promutuel  # tesla car insurance
    - alayacare-insurance  # andy part of family insurance
  groceries:
    - super-c
    - wal-mart
    - provigo
    - couche-tard
    - iga
    - metro
    - maxi
    - ultramar
    - costco
    - fruiterie
    - jarochos
    - epicerie
  grocery_funk:
    - saq
    - dollarama
  restaurants:
    - tim-hortons
    - starbucks
    - mcdonald
    - harveys
    - dairy-queeen
    - dairy-queen
    - uber-eats
    - arriba-burrito
    - sushi
    - gateau
    - subway
    - 7853351-canada  # subway - varennes
    - arahova
    - thai-express
    - tikiming
    - montaza  # small resto in place desormeaux
  pharmacy:
    - jean-coutu
    - pharmaprix
  tools:
    - rona
    - cdn-tire
  mobile-internet:
    - videotron
  online-purchases:
    - amazon
    - apple-store
    - apple.com
    - apple
    - amzn
    - epic-games
    - jb-games
    - michaels  # art and paint store
    - digital-river  # google - fitbit
  extra:
    - winners
    - tabagie
    - bota-bota
    - agence-de-mobilite  # parking mtl
    - lenca-canada
    - saaq
  payment:
    - deposit
    - banking-machine-atm
    - payment
    - paiement
    - scotiabank-transit
    - trsf-from/de-acct  # transfer from bmo to visa

  # BANKING ACCOUNT section start here
  banking_fee:
    - programme-pratique
    - service-charge
    - fixed-monthly-fees
    - interac-e-transfer-service
    - monthly-transaction-fees
  andy_income:
    - infoprime
    - pierre-pouzol
  alex_income:
    - capelya-pedini
    - paie
    - payroll
    - interac-e-transfer
    - alaya-care-inc
  e_transfer:
    - e-transfer
    - interac
  credit_card_pmt:
    - american-expre
    - visa,-bmo
    - preauthorized-debit-sxslx-bns-preauth-pmt
  credit_line:
    - tf-0000000022182671725
    - scotialine

person:
  alex:
    keywords:
      - all_bmo
      - all_nbc
      - fizz
      - hydrosolution
      - preauthorized-debit-02020231221-banque-nationale  # mortgage valois
      - fixed-monthly-fees
      - interac-e-transfer-service
      - monthly-transaction-fees
      - alaya-care-inc
      - alex-deslongchamps-godon  # e-transfert from alex to alex
      - electronic-funds-transfer-preauthorized-debit
    amounts:
      electronic-funds-transfer-preauthorized-debit:
        - 2179.76
  andy:
    keywords:
      - alayacare-insurance
      - electronic-funds-transfer-preauthorized-debit
    amounts:
      electronic-funds-transfer-preauthorized-debit:
        - 120.62
        - 551.75
  payment:
    keywords:
      - deposit
      - banking-machine-atm
      - payment
      - paiement
      - scotiabank-transit
      - trsf-from/de-acct  # transfer from bmo to visa

